shinyPanelPredict <- fluidPage(
  box( width = 12,
    #uiOutput("PredictMusicaList"),
    helpText("Use this tab to calculate the exposures of specified signatures in your samples."),
    selectInput("CosmicCountTable", "Cosmic Count Tables", 
                 choices = list("SBS", "DBS", "INDEL")),
    hidden(checkboxGroupInput("CosmicSBSSigs",
                              "Cosmic V2 SBS Signatures",
                              inline = T,
                              choices = list("1", "2", "3", "4", "5", "6",
                                             "7", "8", "9", "10", "11", "12", 
                                             "13", "14", "15", "16", "17", 
                                             "18", "19", "20", "21", "22", 
                                             "23", "24", "25", "26", "27", 
                                             "28", "29", "30"),
                              selected = list("1", "2", "3", "4", "5", "6",
                                           "7", "8", "9", "10", "11", "12", 
                                           "13", "14", "15", "16", "17", 
                                           "18", "19", "20", "21", "22", 
                                           "23", "24", "25", "26", "27", 
                                           "28", "29", "30"))),
    hidden(checkboxGroupInput("CosmicDBSSigs", 
                              "Cosmic V3 DBS Signatures",
                              inline = T,
                              choices = list("1", "2", "3", "4", "5", "6", 
                                             "7", "8", "9", "10", "11"),
                              selected = list("1", "2", "3", "4", "5", "6", 
                                              "7", "8", "9", "10", "11"))),
    hidden(checkboxGroupInput("CosmicINDELSigs", 
                              "Cosmic V3 INDEL Signatures",
                              inline = T,
                              choices = list("1", "2", "3", "4", "5", "6", 
                                             "7", "8", "9", "10", "11", "12", 
                                             "13", "14", "15"),
                              selected = list("1", "2", "3", "4", "5", "6", 
                                              "7", "8", "9", "10", "11", "12", 
                                              "13", "14", "15"))),                 
    uiOutput("PredictTable"),
    radioButtons("PredictAlgorithm", "Algorithm",
                 choices = list("Latent Dirichlet Allocation (lda)" = "lda", 
                                "decompTumor2Sig",
                                "deconstructSigs")),
    textInput("PredictResultName", "Name for musica result object"),
    textOutput("PredictWarning"),
    # textInput("ChooseCosmicSignatures", 
    #           label = "Choose specific signatures (comma separated), or leave the field empty to select all signatures."),
    actionButton("PredictCosmic", "Predict Signature Exposures"),
    bsTooltip("CosmicCountTable",
              "Select the Cosmic object containing mutational signatures to predict.", 
              placement = "bottom", trigger = "hover", options = NULL),
    bsTooltip("CosmicSBSSigs",
              "Which Cosmic signature to use", 
              placement = "bottom", trigger = "hover", options = NULL),
    bsTooltip("CosmicDBSSigs",
              "Which Cosmic signature to use", 
              placement = "bottom", trigger = "hover", options = NULL),
    bsTooltip("CosmicINDELSigs",
              "Which Cosmic signature to use", 
              placement = "bottom", trigger = "hover", options = NULL),
    bsTooltip("PredictAlgorithm",
              "Algorithm to use for prediction of exposures", 
              placement = "bottom", trigger = "hover", options = NULL),
    bsTooltip("PredictCosmic",
              "Create a musica result object that contains the predicted exposures for samples using an existing set of signatures.", 
              placement = "bottom", trigger = "hover", options = NULL)

  )
)
