shinyPanelPredict <- fluidPage(
  box( 
          #          selectInput("CosmicV2Signatures", 
          #                      h3("Show Cosmic Signatures"), 
          #                      choices = list(
          #           "adrenocortical carcinoma",
          #           "all",
          #           "aml",
          #           "bladder",
          #           "breast",
          #           "cervix",
          #           "chondrosarcoma",
          #           "cll",
          #           "colorectum",
          #           "glioblastoma",
          #           "glioma low grade",
          #           "head and neck",
          #           "kidney chromophobe",
          #           "kidney clear cell",
          #           "kidney papillary",
          #           "liver",
          #           "lung adeno",
          #           "lung  small cell",
          #           "lung  squamous",
          #           "lymphoma b-cell",
          #           "lymphoma hodgkin",
          #           "medulloblastoma",
          #           "melanoma",
          #           "myeloma",
          #           "nasopharyngeal carcinoma",
          #           "neuroblastoma",
          #           "oesophagus",
          #           "oral gingivo-buccal squamous",
          #           "osteosarcoma",
          #           "ovary",
          #           "pancreas",
          #           "paraganglioma",
          #           "pilocytic astrocytoma",
          #           "prostate",
          #           "stomach",
          #           "thyroid",
          #           "urothelial carcinoma",
          #           "uterine carcinoma",
          #           "uterine carcinosarcoma",
          #           "uveal melanoma"
          #         )),
                  #actionButton("CosmicGo", h3("Show Signatures")),
                  radioButtons("CosmicCountTable", "Cosmic Count Table", 
                               choices = list("SBS", "DBS", "INDEL")),
                  hidden(checkboxGroupInput("CosmicSBSSigs", 
                                     "Cosmic V2 SBS Signatures",
                                     inline = T,
                                     choices = list("1", "2", "3", "4", "5", "6",
                                              "7", "8", "9", "10", "11", "12", 
                                              "13", "14", "15", "16", "17", 
                                              "18", "19", "20", "21", "22", 
                                              "23", "24", "25", "26", "27", 
                                              "28", "29", "30"))),
                  hidden(checkboxGroupInput("CosmicDBSSigs", 
                                     "Cosmic V3 DBS Signatures",
                                     inline = T,
                                choices = list("1", "2", "3", "4", "5", "6", 
                                               "7", "8", "9", "10", "11"))),
                  hidden(checkboxGroupInput("CosmicINDELSigs", 
                                     "Cosmic V3 INDEL Signatures",
                                     inline = T,
                             choices = list("1", "2", "3", "4", "5", "6", 
                                            "7", "8", "9", "10", "11", "12", 
                                            "13", "14", "15"))),                 
                  uiOutput("PredictTable"),
                  radioButtons("PredictAlgorithm", h3("Algorithm"),
                               choices = list("lda", 
                                              "decompTumor2Sig",
                                              "deconstructSigs")),
                  # textInput("ChooseCosmicSignatures", 
                  #           label = "Choose specific signatures (comma separated), or leave the field empty to select all signatures."),
                  actionButton("PredictCosmic", "Predict Signatures"),
                  #hidden(textInput("Threshold", "Threshold", value = "0.9")),
                  # hidden(actionButton("Compare", "Compare")),
                  # plotOutput("ComparePlot")
  )
)
