shinyPanelPredict <- fluidPage(
  box( width = 12,
    helpText("Use this tab to calculate the exposures of specified signatures in your samples."),
    uiOutput("PredictedResult"),
    uiOutput("PrecitedSignatures"),
    uiOutput("PredictTable"),
    selectInput("PredictGenomeList", "Reference genome:",
                list("hg19","hg38"), 
                width ='100%'),
    radioButtons("PredictAlgorithm", "Algorithm",
                 choices = list("Latent Dirichlet Allocation (lda)" = "lda", 
                                "decompTumor2Sig",
                                "deconstructSigs")),
    uiOutput("PredictResultName"),
    textOutput("PredictWarning"),
    actionButton("PredictSigs", "Predict Signature Exposures"),
    bsTooltip("CosmicCountTable",
              "Select the Cosmic object containing mutational signatures to predict.", 
              placement = "bottom", trigger = "hover", options = NULL),
    bsTooltip("CosmicSBSSigs",
              "Which Cosmic signature to use", 
              placement = "bottom", trigger = "hover", options = NULL),
    bsTooltip("CosmicDBSSigs",
              "Which Cosmic signature to use", 
              placement = "bottom", trigger = "hover", options = NULL),
    bsTooltip("CosmicINDELSigs",
              "Which Cosmic signature to use", 
              placement = "bottom", trigger = "hover", options = NULL),
    bsTooltip("PredictAlgorithm",
              "Algorithm to use for prediction of exposures", 
              placement = "bottom", trigger = "hover", options = NULL),
    bsTooltip("PredictCosmic",
              "Create a musica result object that contains the predicted exposures for samples using an existing set of signatures.", 
              placement = "bottom", trigger = "hover", options = NULL)

  )
)
