#' @title Retrieve musica from a musica_result object
#' @description  The \code{\linkS4class{musica}} musica contains variants, 
#' count tables, and sample annotations
#' @param result A \code{\linkS4class{musica_result}} object generated by
#' a mutational discovery or prediction tool.
#' @rdname get_musica
#' @return A \code{\linkS4class{musica}} musica object
#' @export
#' @examples
#' data(res)
#' get_musica(res)
setGeneric(
  name = "get_musica",
  def = function(result)
  {
    standardGeneric("get_musica")
  }
)

#' @rdname get_musica
setMethod(
  f = "get_musica",
  signature = "musica_result",
  definition = function(result) {
    return(result@musica)
  }
)

#' @title Retrieve table name used for plotting from a musica_result object
#' @description  The table name
#' @param result A \code{\linkS4class{musica_result}} object generated by
#' a mutational discovery or prediction tool.
#' @rdname table_selected
#' @return Table name used for plotting
#' @export
#' @examples
#' data(res)
#' table_selected(res)
setGeneric(
  name = "table_selected",
  def = function(result)
  {
    standardGeneric("table_selected")
  }
)

#' @rdname table_selected
setMethod(
  f = "table_selected",
  signature = "musica_result",
  definition = function(result) {
    return(result@table_name)
  }
)

#' @title Retrieve exposures from a musica_result object
#' @description  The \code{exposure} matrix contains estimated amount of
#' each signature for each sample. Rows correspond to each signature and
#' columns correspond to each sample.
#' @param result A \code{\linkS4class{musica_result}} object generated by
#' a mutational discovery or prediction tool.
#' @rdname exposures
#' @return A matrix of exposures
#' @export
#' @examples
#' data(res)
#' exposures(res)
setGeneric(
  name = "exposures",
  def = function(result)
  {
    standardGeneric("exposures")
  }
)

#' @rdname exposures
setMethod(
  f = "exposures",
  signature = "musica_result",
  definition = function(result) {
    return(result@exposures)
  }
)

#' @rdname exposures
#' @param result A \code{\linkS4class{musica_result}} object generated by
#' a mutational discovery or prediction tool.
#' @param value A matrix of samples by signature exposures
#' @export
#' @examples
#' data(res)
#' exposures(res) <- matrix()
setGeneric(
  name = "exposures<-",
  def = function(result, value)
  {
    standardGeneric("exposures<-")
  }
)

#' @rdname exposures
setReplaceMethod(
  f = "exposures",
  signature = c("musica_result", "matrix"),
  definition = function(result, value)
  {
    result@exposures <- value
    return(result)
  }
) 

#' @title Retrieve signatures from a musica_result object
#' @description  The \code{signature} matrix contains the probability of
#' mutation motif in each sample. Rows correspond to each motif and
#' columns correspond to each signature.
#' @param result A \code{\linkS4class{musica_result}} object generated by
#' a mutational discovery or prediction tool.
#' @rdname signatures
#' @return A matrix of mutational signatures
#' @export
#' @examples
#' data(res)
#' signatures(res)
setGeneric(
  name = "signatures",
  def = function(result)
  {
    standardGeneric("signatures")
  }
)

#' @rdname signatures
setMethod(
  f = "signatures",
  signature = "musica_result",
  definition = function(result) {
    return(result@signatures)
  }
)

#' @rdname signatures
#' @param result A \code{\linkS4class{musica_result}} object generated by
#' a mutational discovery or prediction tool.
#' @param value A matrix of motifs counts by samples
#' @export
#' @examples
#' data(res)
#' signatures(res) <- matrix()
setGeneric(
  name = "signatures<-",
  def = function(result, value)
  {
    standardGeneric("signatures<-")
  }
)

#' @rdname signatures
setReplaceMethod(
  f = "signatures",
  signature = c("musica_result", "matrix"),
  definition = function(result, value)
  {
    result@signatures <- value
    return(result)
  }
) 

#' @title Retrieve umap list from a musica_result object
#' @description  The \code{signature} matrix contains the probability of
#' mutation motif in each sample. Rows correspond to each motif and
#' columns correspond to each signature.
#' @param result A \code{\linkS4class{musica_result}} object generated by
#' a mutational discovery or prediction tool.
#' @rdname umap
#' @return A list of umap dataframes
#' @export
#' @examples
#' data(res)
#' umap(res)
setGeneric(
  name = "umap",
  def = function(result)
  {
    standardGeneric("umap")
  }
)

#' @rdname umap
setMethod(
  f = "umap",
  signature = "musica_result",
  definition = function(result) {
    return(result@umap)
  }
)

#' @rdname umap
#' @param result A \code{\linkS4class{musica_result}} object generated by
#' a mutational discovery or prediction tool.
#' @param value A list of umap dataframes
#' @export
#' @examples
#' data(res)
#' umap(res) <- matrix()
setGeneric(
  name = "umap<-",
  def = function(result, value)
  {
    standardGeneric("umap<-")
  }
)

#' @rdname umap
setReplaceMethod(
  f = "umap",
  signature = c("musica_result", "matrix"),
  definition = function(result, value)
  {
    result@umap <- value
    return(result)
  }
) 

