#' @import ggplot2 
#' @importFrom rlang .data
#' @import dplyr
#' @import tidyr
#' @import tidyverse 
NULL


#' Plot reconstruction error for a sample
#' 
#' Displays the observed distribution of counts for each mutation type, 
#' the distribution of reconstructed counts for each mutation type using 
#' the inferred mutational signatures, and the difference between the 
#' two distributions. 
#'
#' @param result A \code{\linkS4class{musica_result}} object generated by
#' a mutational discovery or prediction tool.
#' @param sample Name of the sample within the
#' \code{\linkS4class{musica_result}} object.
#' @param plotly If \code{TRUE}, the the plot will be made interactive
#' using \code{\link[plotly]{plotly}}. Default \code{FALSE}.
#' @return Generates a ggplot or plotly object
#' @examples
#' data(res)
#' plot_sample_reconstruction_error(res, "TCGA-ER-A197-06A-32D-A197-08")
#' @export
plot_sample_reconstruction_error <- function(result, sample,
                                             plotly = FALSE) {
    signatures <- .extract_count_table(get_musica(result), 
                                       table_selected(result))[, sample, 
                                                               drop = FALSE]
    sample_name <- colnames(signatures)
    reconstructed <- reconstruct_sample(result, sample)
    sigs <- cbind(signatures, reconstructed, signatures - reconstructed)
    colnames(sigs) <- c("Counts", "Reconstructed", "Difference")
    
    recontruct_result <- methods::new("musica_result",
                                      signatures = sigs,
                                      exposures = matrix(), algorithm = "NMF",
                                      musica = get_musica(result),
                                      table_name = table_selected(result))
    plot_signatures(recontruct_result, same_scale = FALSE) +
        ggplot2::ggtitle("Reconstruction error", subtitle = sample_name) + ylab("")
}
