#' @importFrom ComplexHeatmap Heatmap 
#' @importFrom ComplexHeatmap HeatmapAnnotation
#' @importFrom rapportools is.boolean
#' 
#' @title Plot heatmaps using the exposures matrix
#' 
#' @description The exposures for different signatures can be visualized using a heatmap with this function.
#' Heatmaps make it easier to visualize the data by representing the magbitude of exposure values
#' as color in 2-dimensions. The variation in color intensity can help see if the exposures are clustered
#' or how they vary over space. Exposures can be normalized by providing the \code{proportional} argument.
#' Column annotations can also be seen by passing the \code{col_annot} argument.
#'  
#' @param result A \code{\linkS4class{musica_result}} object generated by
#' a mutational discovery or prediction tool.
#' @param proportional If \code{TRUE}, then the exposures will be normalized
#' to between 0 and 1 by dividing by the total number of counts for each sample.
#' Default \code{FALSE}.
#' @param col_annot Boolean check. If \code{True}, column annotations extracted from the musicatk object 
#' and passed as a HeatmapAnnotation to the Heatmap function.
#' Default \code{FALSE}.
#' @param col_samps Argument containing user given column annotations. It is passed on to the Heatmap function 
#' as an S4 object of class Heatmap annotation.
#' @param annotations Column annotations extracted from the musicatk object 
#' @return Generates a heatmap for using the exposure matrix.
#' @examples result <- readRDS(system.file("testdata", "res_annot.rds",
#' package = "musicatk"))
#' exp <- exposures(result)
#' ComplexHeatmap::Heatmap(exp)
#' @export



plot_heatmap <- function(result, 
                         proportional = FALSE,
                         col_annot = FALSE,
                         col_samps,
                         ...){
  
  exp <- exposures(result) #extracting the exposures matrix
  annotations <- result@musica@sample_annotations #Extracting annotations from musicatk object
  
  #Checking if proportional argument correct
  if(!rapportools::is.boolean(proportional))  {
      stop("The 'proprotional' parameter must be a boolean TRUE or FALSE.")
  }
 
  if(proportional == TRUE){
    exp <- sweep(exp, 2, colSums(exp), FUN = "/") #normalizing 
  }
  
  #Checking if col_annot argument correct
  if(!is.boolean(col_annot))  {
    
    stop("The 'col_annot' parameter must be a boolean TRUE or FALSE.")
    
  }
  
  if(col_annot == TRUE){
    
    ha <- ComplexHeatmap::HeatmapAnnotation(df = annotations)
    ComplexHeatmap::Heatmap(exp,name = 'exposures',show_column_names = FALSE,top_annotation = ha,...)
    
  }
  else if(col_annot == FALSE){
    
    if(missing(col_samps)){
      ComplexHeatmap::Heatmap(exp,name = 'exposures',show_column_names = FALSE,...)
    }
    
    else if(!is.null(col_samps)){
      ha <- ComplexHeatmap::HeatmapAnnotation(df = col_samps)
      ComplexHeatmap::Heatmap(exp,name = 'exposures',show_column_names = FALSE,top_annotation = ha,...)
    
    }
  }
}
